#!/usr/bin/env python3
"""Attach concrete missing assertions/proposed tests; never mark final gates passed."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
# Proposed names/files describe work to do; they are not execution evidence.
MISSING={
"cli:search":["Positive enrich-top invokes only selected readers, preserves failed captures and exact metadata; no native reader implementation yet", "For each inventoried search flag/default, measure paired JSON/text/exit/negative-limit cases on all nine providers; cover UTF8/signed-bound parser and explicit safety differences"],
"cli:read":["Implement Jina/auto fallback on FetchError only; direct is scoped implemented, remaining malformed URL/model/codec behavior must match accepted policies", "Compare header/meta charset, HTML/PDF/text extraction, cache miss/hit/refresh write failure and original archive contents on eight populated tables"],
"cli:openalex expand":["Implement work/DOI quoting, incoming/outgoing/both graph traversal and 50-work bound; match cursor/dedup/metadata", "Compare fresh/stale/offline graph-cache key/version/partial-error semantics and copy preservation without live OpenAlex calls"],
"cli:collect":["Implement runs/search_results/pages transaction and exact CLI outputs for mixed successful/failed URL captures", "Compare UTF8 Markdown evidence, reader fallback, report-write failure and rollback against copied synthetic histories"],
"cli:query":["Compare invalid FTS expression, all punctuation/empty/C0 whitespace, signed-i64 endpoints and UTF8 argv with explicit parser policy", "Verify query refusal on future/old-column schema and no source/sidecar damage on broken stdout or interrupt"],
"cli:plan":["Compare absent versus explicit year, duplicate/whitespace subqueries and i64 endpoints against the declared Python numeric-bound policy", "Measure default/text/JSON/invalid-argument coverage and OS newline/UTF8 stdout with exact source evidence"],
"cli:repos scan":["Implement traversal/skip rules, symlink loops/escape policy and mixed UTF8/invalid-byte file handling on an owned tree", "Assert size/mtime/hash/context invalidation, deletion and FTS insert/update/delete transaction rollback on interrupted scans"],
"cli:repos query":["Compare precedence of inline/explicit repo/path filters, literal percent/underscore/backslash LIKE escaping and context weights at signed bounds", "Verify old/future-schema refusal and broken stdout/interrupt preserve the complete copied archive"],
"cli:feeds add":["Compare absent/empty/duplicate URL/title and empty/UTF8 archive argv; retain every existing health field/item and source count", "Verify read-only/future/old-column archive failures and transaction/sidecar preservation under interrupt"],
"cli:feeds refresh":["Compare DTD/entity/date/non-object JSONFeed and malformed HTML/file URI boundaries with named rejection policies approved", "Assert source selection/order and batch failure/write rollback retain previous items/health; cap-one-over body/global time at owned transport"],
"cli:feeds query":["Compare all FTS punctuation/empty/Unicode/signed endpoints with exact title/summary/source metadata and bm25 order", "Assert malformed/null-date schema rows and read-only/future/old-column refusal do not mutate data"],
"cli:sources list":["Compare malformed overlay root/fields, duplicate identity and trust-score types, stable name ordering and signed endpoints", "Measure every inventory flag/default/JSON/text/error shape and Unicode/OS path behavior against accepted policies"],
"cli:sources match":["Compare userinfo/IPv6/IDNA, slashless URLs, C0 cleaning, params/ports and prefix boundaries against literal urllib semantics", "Assert malformed overlay error behavior and no URI canonicalization changes trust/category matches"],
"cli:issues ingest":["Implement from-json issue/PR normalization including labels/priority/status, unknown/duplicate fields and malformed records", "Implement bounded owned gh transcript auth/timeout/nonzero behavior and atomic project-item/FTS rollback"],
"cli:issues query":["Compare FTS label/item_key fields, unknown/null metadata and signed/empty query endpoints", "Assert read-only/future/old-column schema and stdout/interrupt failures retain copied archive data"],
"cli:issues report":["Implement radar Markdown grouping and priority/status/phase/number tie ordering with duplicate labels", "Compare empty/mixed Unicode report, JSON/text/exit and output-path write failure without source mutation"],
"cli:brief":["Implement local/web source selection, plan, dedup/quality scores and top-N report metadata", "Compare no-web/partial-network/error cases and exact report/provenance on populated copied histories"],
"cli:investigate":["Implement selected URL captures, source lineage, checklist/evidence fields and reader-error retention", "Compare failed report/capture writes, partial success, UTF8 Markdown and copied archive rollback"],
"cli:doctor":["Implement provider status/configuration posture without reading secrets or issuing requests by default", "Compare SQLite FTS probe and explicitly requested local SearXNG preflight, missing program/key/env failures and JSON/text/exit"],
"cli:engines":["Expand recent-window tests at four/five samples, exact 0.5 failure/0.2 useful/5000ms latency thresholds, duplicate providers and nearest-rank p95", "Compare 500-row prune, newest-error selection, ledger write/read failure and no implicit archive creation in the library"],
"cli:eval":["Implement native deterministic metrics, fixtures, threshold-80 pass/fail/exit and report serialization", "Compare all inventoried defaults/limits/output paths and exact Markdown; repeat counts must be deterministic, never live/model calls"],
"cli:mcp":["Implement nine inventoried tool names/descriptions/input schemas and every mapped command JSON/error shape; native MCP currently absent", "Compare initialize/list/call/notifications/unknown methods/tools and fragmented/malformed UTF8 Content-Length CRLF plus NDJSON; stdout contains protocol only"],
"provider:ddg":["Extend HTML parser oracle to malformed nesting/entities/attributes/raw-text boundaries and URL/query scalar edge cases", "Assert invalid-byte env, remaining charset/redirect/proxy behavior and discard/freshness metadata through named approved policies"],
"provider:github":["Implement/test actual Windows PATH/PATHEXT/child-group/pipe lifecycle; Linux target execution is missing", "Compare remaining gh/REST malformed numeric/container/date representations, missing/replaced executable and signal-before-fallback/no partial success"],
"provider:github_code":["Compare 100/page and 10-page boundaries with malformed collection/numeric/date fields and rank holes after discard", "Verify invalid-byte token/env, auth/422/late error and cap-one-over output/JSON depth against approved policies"],
"provider:jina":["Approve or repair the five named typed_fields/typed_collections/strict_json_constants/strict_unicode/depth_limit policies and their 55 recorded differences", "Compare remaining query/env-byte/charset/scalar branches and secret-bearing cross-origin redirects; no live service claim"],
"provider:searxng":["Approve or repair named JSON shape/constants/Unicode/depth differences; cover all categories/engines/language/time/safesearch combinations", "Compare endpoint/env-byte/charset/redirect and late-page error/candidate/maximum-response boundaries without live queries"],
"provider:brave":["Approve or repair named JSON shape/constants/Unicode/depth differences; cover country/search/ui language/freshness/safesearch boundaries", "Compare invalid-byte key/env and same/cross-host/port/return redirects; Subscription-Token must never restore across an origin change"],
"provider:openalex":["Test documented decoded-position/aggregate results/pages/bytes cap and one-over before allocation, huge requested limit and interrupted accumulation; cap policy is not chosen", "Cover remaining scalar/Unicode mapping/env-byte and authenticated redirect branches; graph/quoting/cache are separate unimplemented commands"],
"provider:meta":["Expand duplicate/weak/all-weak recent-window thresholds and all inventoried config/CLI flags at signed/invalid-byte boundaries", "Assert interrupt while ledger is busy/before/during commit, worker panic/redaction and no partial-success publication; worker-time signal fixtures alone do not close commit/crash semantics"],
"gate:storage":["Kill only an owned migration child before/after backup/transaction/fsync/publish; restart/dry-run/idempotence/rollback and occupied WAL/SHM/journal/race retain source fingerprints", "Execute known old/upgraded/future schema variants and all native writers against populated eight-table/41-object/FTS copies on actual targets; real cutover remains unauthorized"],
"gate:network":["Assert resolver/client-startup/global timeout, interrupt/broken-pipe and remaining charset/proxy/env/credential redirect cases; HTTP2/3 stay disabled", "Bound aggregate provider results/abstract allocations and observe peak memory/deadline; accepted per-response cap is not a total-search bound"],
"gate:release":["Run pinned setup/build/test/release and process/path/newline/signal fixtures on actual Mac/Windows/Linux, after target authorization/cost approval", "Verify package contents, bundled SQLite/TLS dependency LICENSE/NOTICE and no Python runtime subprocess; deterministic build evidence requires artifact hashes"],
"gate:reports":["Implement each downstream native report, then compare UTF8 Markdown sections/order/citations/checklists/evidence models to Python", "Normalize only declared owned paths/timestamps/measured clock inputs after exact algorithm replay; never titles/URLs/health/scores/ranks/provenance"],
"gate:live":["Record a separately authorized bounded read-only check for each configured free provider with fresh auth/rate/availability observations", "No paid/unpriced API, real key/vault, new auth/network or large search is authorized; absent permission/config remains explicitly unverified"],
}
def main():
    path=ROOT/"docs/migration/golden-matrix.json";matrix=json.loads(path.read_text())
    assert set(MISSING)=={r["id"] for r in matrix["rows"]}
    for row in matrix["rows"]:
        row["missing_assertions"]=MISSING[row["id"]]
        slug=row["id"].replace(":","-").replace(" ","-")
        row["next_tests"]=[{"id":slug+"-remaining-contract", "status":"blocked" if row["id"]=="gate:live" else "proposed", "planned_file":"scripts/migration/final_contract_"+slug.replace("-","_")+".py", "assertions":MISSING[row["id"]], "execution_evidence":False}]
        if row["id"]=="gate:live":row["next_tests"][0]["blocked_reason"]="Separate live authorization/configuration/cost evidence absent; paid/unpriced calls prohibited"
        row["scope_acceptance"]={"full_ready":False,"status":"passed_scopes" if row.get("case_evidence") else "not_allocated", "scopes":[{"case_evidence_id":c["id"],"scope":c["scope"],"status":c["status"]} for c in row.get("case_evidence",[])]}
        row["close_when"]="Execute every missing assertion with exact-source evidence, approve named contract differences, and satisfy the applicable target/storage/network/report/release/live final scope. Scoped cases alone never close this row."
    path.write_text(json.dumps(matrix,ensure_ascii=False,indent=2)+"\n")
    print("concrete remaining assertions and proposed tests:",len(matrix["rows"]),"rows; no final gate changed")
if __name__=="__main__":main()
